import { fabric } from "https://cdn.jsdelivr.net/npm/fabric@7.4.0/+esm";
const $=id=>document.getElementById(id),canvas=new fabric.Canvas("editorCanvas",{preserveObjectStacking:true,selection:true});let history=[],future=[],restoring=false;
function status(s){$("status").textContent=s}function toast(s){let t=$("toast");t.textContent=s;t.className="show";setTimeout(()=>t.className="",2200)}
function snapshot(){if(restoring)return;const j=JSON.stringify(canvas.toJSON(["name"]));if(history.at(-1)!==j){history.push(j);if(history.length>60)history.shift();future=[]}}
function restore(j){restoring=true;canvas.loadFromJSON(JSON.parse(j)).then(()=>{canvas.renderAll();sync();restoring=false})}
function fit(){const st=$("stage"),z=Math.min((st.clientWidth-60)/canvas.width,(st.clientHeight-60)/canvas.height,1);canvas.setZoom(z);canvas.setDimensions({width:canvas.width*z,height:canvas.height*z},"cssOnly");$("zoomLabel").textContent=Math.round(z*100)+"%"}
function resizeCanvas(){const w=+$("cw").value||1024,h=+$("ch").value||1024;canvas.setDimensions({width:w,height:h});$("dimensions").textContent=w+" × "+h;fit()}
async function addImage(url,name="image"){const img=await fabric.FabricImage.fromURL(url,{crossOrigin:"anonymous"}),{w,h}= {w:+$("cw").value||1024,h:+$("ch").value||1024},s=Math.min(w*.8/img.width,h*.8/img.height,1);img.set({left:(w-img.width*s)/2,top:(h-img.height*s)/2,scaleX:s,scaleY:s,name});canvas.add(img);canvas.setActiveObject(img);canvas.renderAll();snapshot();sync();$("dropHint").style.display="none";return img}
async function upload(f){if(!f)return;status("Loading…");const u=URL.createObjectURL(f);await addImage(u,f.name);URL.revokeObjectURL(u);status("Ready")}
$("uploadBtn").onclick=()=>$("fileInput").click();$("fileInput").onchange=e=>upload(e.target.files[0]);$("stage").ondragover=e=>{e.preventDefault();$("stage").classList.add("drop-active")};$("stage").ondragleave=()=>$("stage").classList.remove("drop-active");$("stage").ondrop=e=>{e.preventDefault();$("stage").classList.remove("drop-active");upload(e.dataTransfer.files[0])};
async function removeBg(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return toast("Select an image first");$("bgBtn").disabled=true;status("AI background removal…");try{const {default:removeBackground}=await import("https://cdn.jsdelivr.net/npm/@imgly/background-removal@1.7.0/+esm");const b=await removeBackground(o.getElement(),{device:"gpu",output:{format:"image/png",quality:1,type:"foreground"},progress:(k,c,t)=>status("AI "+k+" "+c+"/"+t)}),u=URL.createObjectURL(b),n=await fabric.FabricImage.fromURL(u);n.set({left:o.left,top:o.top,scaleX:o.scaleX,scaleY:o.scaleY,angle:o.angle,opacity:o.opacity,name:(o.name||"image")+"_cutout"});canvas.remove(o);canvas.add(n);canvas.setActiveObject(n);canvas.renderAll();snapshot();await vaultPut(b,n.name+".png");toast("Background removed");status("Ready");URL.revokeObjectURL(u)}catch(e){console.error(e);toast("AI removal failed; original preserved");status("Ready")}finally{$("bgBtn").disabled=false}}
$("bgBtn").onclick=removeBg;
function sync(){const o=canvas.getActiveObject();$("propsEmpty").classList.toggle("hidden",!!o);$("props").classList.toggle("hidden",!o);if(!o)return;for(const [id,val] of [["px",o.left||0],["py",o.top||0],["pw",o.getScaledWidth()||0],["ph",o.getScaledHeight()||0],["prot",o.angle||0],["pop",o.opacity??1]])$(id).value=Math.round(val*100)/100;$("imageControls").classList.toggle("hidden",o.type!=="image")}
function update(){const o=canvas.getActiveObject();if(!o)return;o.set({left:+$("px").value||0,top:+$("py").value||0,angle:+$("prot").value||0,opacity:+$("pop").value});const w=+$("pw").value,h=+$("ph").value;if(w>0)o.scaleX=w/o.width;if(h>0)o.scaleY=h/o.height;canvas.requestRenderAll();snapshot()}["px","py","pw","ph","prot","pop"].forEach(id=>$(id).onchange=update);
$("deleteBtn").onclick=()=>{const o=canvas.getActiveObject();if(o){canvas.remove(o);snapshot();sync()}};$("duplicateBtn").onclick=async()=>{const o=canvas.getActiveObject();if(!o)return;const c=await o.clone();c.set({left:(o.left||0)+20,top:(o.top||0)+20});canvas.add(c);canvas.setActiveObject(c);snapshot()};
$("textBtn").onclick=()=>{const t=new fabric.IText("Game Asset",{left:100,top:100,fill:"#fff",fontSize:64,fontFamily:"Arial",fontWeight:"700"});canvas.add(t);canvas.setActiveObject(t);snapshot()};
$("rectBtn").onclick=()=>{const r=new fabric.Rect({left:100,top:100,width:240,height:160,fill:"#3b82f6",rx:16,ry:16});canvas.add(r);canvas.setActiveObject(r);snapshot()};
function filters(){const o=canvas.getActiveObject();if(!o||o.type!=="image")return;o.filters=[new fabric.filters.Brightness({brightness:+$("brightness").value}),new fabric.filters.Contrast({contrast:+$("contrast").value}),new fabric.filters.Saturation({saturation:+$("saturation").value}),new fabric.filters.Blur({blur:+$("blur").value})].filter((f,i)=>+[$("brightness").value,$("contrast").value,$("saturation").value,$("blur").value][i]!==0);o.applyFilters();canvas.renderAll();snapshot()}["brightness","contrast","saturation","blur"].forEach(id=>$(id).oninput=filters);
$("resetFilters").onclick=()=>{const o=canvas.getActiveObject();if(o?.type==="image"){o.filters=[];o.applyFilters();["brightness","contrast","saturation","blur"].forEach(id=>$(id).value=0);canvas.renderAll();snapshot()}};
$("undoBtn").onclick=()=>{if(history.length<2)return;future.push(history.pop());restore(history.at(-1))};$("redoBtn").onclick=()=>{const n=future.pop();if(n){history.push(n);restore(n)}};
async function exportPng(){const b=await canvas.toBlob({format:"png",multiplier:1});download(b,"asset.png");await vaultPut(b,"asset.png");toast("Saved to Asset Vault")}
function download(b,n){const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}$("exportBtn").onclick=exportPng;
function db(){return new Promise((res,rej)=>{const r=indexedDB.open("asset-forge-v1",1);r.onupgradeneeded=()=>r.result.createObjectStore("assets",{keyPath:"id"});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function vaultPut(blob,name){const d=await db(),tx=d.transaction("assets","readwrite");tx.objectStore("assets").put({id:crypto.randomUUID(),name,blob,created:Date.now()});tx.oncomplete=renderVault}
async function renderVault(){const d=await db(),r=d.transaction("assets","readonly").objectStore("assets").getAll();r.onsuccess=()=>{$("vault").innerHTML="";for(const a of r.result.sort((x,y)=>y.created-x.created)){const el=document.createElement("div");el.className="asset";el.innerHTML="<img><small></small>";el.querySelector("img").src=URL.createObjectURL(a.blob);el.querySelector("small").textContent=a.name;el.onclick=async()=>{const u=URL.createObjectURL(a.blob);await addImage(u,a.name);URL.revokeObjectURL(u)};$("vault").appendChild(el)}}}
$("clearVaultBtn").onclick=async()=>{const d=await db();d.transaction("assets","readwrite").objectStore("assets").clear();renderVault()};
$("newBtn").onclick=()=>{canvas.clear();history=[];future=[];snapshot();$("dropHint").style.display="block"};$("saveBtn").onclick=()=>{const data={version:1,width:+$("cw").value,height:+$("ch").value,canvas:canvas.toJSON(["name"])};download(new Blob([JSON.stringify(data)],{type:"application/json"}),"asset-forge-project.json")};$("openBtn").onclick=()=>$("projectInput").click();$("projectInput").onchange=async e=>{const f=e.target.files[0];if(!f)return;const d=JSON.parse(await f.text());$("cw").value=d.width;$("ch").value=d.height;resizeCanvas();restore(JSON.stringify(d.canvas));$("dropHint").style.display="none"};
$("applySize").onclick=resizeCanvas;$("fitBtn").onclick=fit;
$("spriteBtn").onclick=async()=>{const cols=Math.max(1,+$("cols").value||1),rows=Math.max(1,+$("rows").value||1),w=+$("cw").value||1024,h=+$("ch").value||1024,b=await canvas.toBlob({format:"png"}),img=await createImageBitmap(b),out=new OffscreenCanvas(w,h),ctx=out.getContext("2d"),cw=Math.floor(w/cols),ch=Math.floor(h/rows);for(let i=0;i<cols*rows;i++)ctx.drawImage(img,0,0,img.width,img.height,(i%cols)*cw,Math.floor(i/cols)*ch,cw,ch);const sb=await out.convertToBlob({type:"image/png"});download(sb,"sprite-sheet.png");await vaultPut(sb,"sprite-sheet.png");toast("Sprite sheet created")};
$("cropBtn").onclick=()=>toast("Crop workflow is reserved for the next hardening pass; no destructive crop is performed.");
canvas.on("object:added",()=>{if(!restoring)snapshot();sync()});canvas.on("object:modified",()=>{if(!restoring)snapshot();sync()});canvas.on("selection:created",sync);canvas.on("selection:updated",sync);canvas.on("selection:cleared",sync);window.onresize=fit;document.onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==="z"){e.preventDefault();$("undoBtn").click()}if((e.ctrlKey||e.metaKey)&&e.key==="y"){e.preventDefault();$("redoBtn").click()}if(e.key==="Delete")$("deleteBtn").click()};
resizeCanvas();snapshot();renderVault();
